name: Publish Docker Image

on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  id-token: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        install: true
        driver-opts: image=moby/buildkit:master
        use: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Check if current tag is the highest
      id: highest_tag_check
      run: |
        git fetch --tags
        HIGHEST_TAG=$(git tag | sort -V | tail -n 1)
        if [ "${GITHUB_REF#refs/tags/}" == "$HIGHEST_TAG" ]; then
          echo "::set-output name=is_highest::true"
        else
          echo "::set-output name=is_highest::false"
        fi

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ github.actor }}/${{ vars.IMAGE_NAME }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
        flavor: latest=${{ steps.highest_tag_check.outputs.is_highest }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: ${{ steps.setup-buildx.outputs.nodes.platforms }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}